import { parse, resolve } from 'path';
import { existsSync, readdirSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { config } from './config';

const getBlockEntry = (blockName: string, fileType: string): string | null => {
  const filePath = resolve(__dirname, `src/blocks/${blockName}/${blockName}.${fileType}`);
  return existsSync(filePath) ? filePath : null;
};

const getTsEntry = (blockName: string): Record<string, string> | null => {
  const tsPath = getBlockEntry(blockName, 'ts');
  return tsPath !== null ? { [blockName]: tsPath } : null;
};

const getBlockNamesFromSrcFolder = (): string[] => {
  const blocksPath = resolve(__dirname, 'src/blocks');
  try {
    return readdirSync(blocksPath);
  } catch (error) {
    console.error(`Failed to read directory at ${blocksPath}`, error);
    return [];
  }
};

export const generateBlockEntries = () => {
  const blockNames = getBlockNamesFromSrcFolder();
  let entries = {};
  blockNames.forEach((blockName) => {
    const tsEntry = getTsEntry(blockName);
    entries = { ...entries, ...tsEntry };
  });
  return entries;
};

export const generateIconNameType = () => {
  try {
    const { iconsDirPath, iconsTypesPath } = config;
    const iconFiles = readdirSync(iconsDirPath).filter((file) => file.endsWith('.svg'));

    const icons = iconFiles.map((file) => parse(file).name.replace(/[^a-zA-Z0-9-]/g, ''));
    const typeComment = `/*
    * DO NOT EDIT THIS FILE DIRECTLY.
    * This file is auto-generated by the vite.helpers.ts script.
    */`;
    const typeDefinition = `${typeComment}
    export type IconName = '${icons.join("'  | \n'")}';\n`;

    writeFileSync(iconsTypesPath, typeDefinition);

    const prettierConfigPath = './.prettierrc';
    execSync(`npx prettier --write ${iconsTypesPath} --config ${prettierConfigPath}`);

    console.log('Icon type definitions generated and formatted successfully.');
  } catch (error) {
    console.error('Error generating and formatting icon type definitions:', error);
  }
};
