name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Project
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Continuous Integration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci && npm run build && npm run lint
      - run: npm run build --if-present
      - run: npm run lint
      - name: LS
        run: ls -la

      # - name: Display event name
      #   run: echo "github.event_name=${{ github.event_name }}"
      # - name: Commit build artifacts (dist, devdist, docs, coverage)
      #   if: env.CI_COMMIT_AUTHOR != 'auto' && github.event_name != 'pull_request'
      #   run: |
      #     git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
      #     git config --global user.email "eds-editorial-ci@diva-e.com"
      #     git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
      #     git push
