name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: npm ci, build, and lint
    - run: npm ci
    - run: npm run build --if-present 
    - run: npm run lint
    - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Upload dist
          path: dist

